version: "3"

tasks:
  migration:
    cmds:
      - createdb -h localhost -p 5432 -U postgres blog
      - psql -h localhost -p 5432 -U postgres blog < .\model\Init_model.sql
    silent: true
  demigration:
    cmds:
      - psql -h localhost -p 5432 -U postgres < .\model\Delete_model.sql
    silent: true
  test:
    cmds:
      - go test -v -cover ./...
    silent: true
  run:
    cmds:
      - go run ./cmd/server/main.go
    silent: true
  build:
    cmds:
      - GOOS=linux go build -ldflags="-s -w" -o main ./cmd/server/main.go 
    silent: true

